//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Barbershop.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        public int ID_Account { get; set; }
        public Nullable<int> ID_Employee { get; set; }
        public string Login_ { get; set; }
        public string Password_ { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
