//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Barbershop.database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_BarbershopEntities : DbContext
    {
        private static DB_BarbershopEntities _context;
        public DB_BarbershopEntities()
            : base("name=DB_BarbershopEntities")
        {
        }

        public static DB_BarbershopEntities GetContext() 
        {
            if (_context == null)
                _context = new DB_BarbershopEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Positions> Positions { get; set; }
        public virtual DbSet<Records> Records { get; set; }
        public virtual DbSet<Service_records> Service_records { get; set; }
        public virtual DbSet<Services_> Services_ { get; set; }
        public virtual DbSet<Stocks> Stocks { get; set; }
        public virtual DbSet<Type_services> Type_services { get; set; }
    }
}
