//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Barbershop.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Records
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Records()
        {
            this.Service_records = new HashSet<Service_records>();
        }
    
        public int ID_Record { get; set; }
        public int ID_Employee { get; set; }
        public int ID_Client { get; set; }
        public System.DateTime Date_ { get; set; }
        public System.TimeSpan Time_ { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Employees Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_records> Service_records { get; set; }
    }
}
