//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Barbershop.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Services_()
        {
            this.Service_records = new HashSet<Service_records>();
        }
    
        public int ID_Service { get; set; }
        public int ID_Type { get; set; }
        public string Title { get; set; }
        public double Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_records> Service_records { get; set; }
        public virtual Type_services Type_services { get; set; }
    }
}
