//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Barbershop.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_records
    {
        public int ID_Service_record { get; set; }
        public int ID_Record { get; set; }
        public int ID_Service { get; set; }
        public Nullable<int> ID_Stock { get; set; }
        public double Cost { get; set; }
    
        public virtual Records Records { get; set; }
        public virtual Services_ Services_ { get; set; }
        public virtual Stocks Stocks { get; set; }
    }
}
